services:
  app:
    build: .
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=elga_user
      - POSTGRES_PASSWORD=elga_pass
      - POSTGRES_DB=elga_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: