services:
  app:
    build: .
    command: sh -c "npx prisma migrate deploy && npm start"
    expose:
      - "3000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=elga_user
      - POSTGRES_PASSWORD=elga_pass
      - POSTGRES_DB=elga_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 