services:
  app:
    build: 
      context: .
      args:
        - NEXT_PUBLIC_INVITE_BASE_URL=${NEXT_PUBLIC_INVITE_BASE_URL}
        - INVITE_BASE_URL=${INVITE_BASE_URL}
        - WEBHOOK_URL=${WEBHOOK_URL}
        - WEBHOOK_PRESELECTION_PROMOTED_URL=${WEBHOOK_PRESELECTION_PROMOTED_URL}
        - NOME_EVENTO=${NOME_EVENTO}
    ports:
      - "3001:3001"
    expose:
      - "3001"
    environment:
      - NEXT_PUBLIC_INVITE_BASE_URL=${NEXT_PUBLIC_INVITE_BASE_URL}
      - INVITE_BASE_URL=${INVITE_BASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PRESELECTION_PROMOTED_URL=${WEBHOOK_PRESELECTION_PROMOTED_URL}
      - NOME_EVENTO=${NOME_EVENTO}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=elga_user
      - POSTGRES_PASSWORD=elga_pass
      - POSTGRES_DB=elga_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: