services:
  app-dev:
    image: node:18-alpine
    working_dir: /app
    command: sh -lc "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=1
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_INVITE_BASE_URL=${NEXT_PUBLIC_INVITE_BASE_URL}
      - INVITE_BASE_URL=${INVITE_BASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PRESELECTION_PROMOTED_URL=${WEBHOOK_PRESELECTION_PROMOTED_URL}
      - NOME_EVENTO=${NOME_EVENTO}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-elga_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-elga_pass}
      - POSTGRES_DB=${DB_NAME:-elga_db}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  node_modules:
  db_data:


